spring:
  application:
    name: cache-test
  datasource:
    url: jdbc:mariadb://localhost:3306/ext
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE

server:
  port: 8888

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE